version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: edge.projectdemo1.integrations:test
  packages:
  - name: EdgeProjectDemo1
    version: "1.0"
- serviceName: edge.projectdemo1.integrations:testdb
  packages:
  - name: EdgeProjectDemo1
    version: "1.0"
